### ISSUE TITLE
create branch MAIN from MASTER

### ISSUE THREAD

**Issue by PaulCharlton** [apptainer/sif#118]
create branch MAIN from MASTER to be consistent with current practices on apptainer and other projects

**Comment by PaulCharlton** [comment]
@DrDaveD @cclerget @ikaneshiro @kmuriki lmk what you think

**Comment by DrDaveD** [comment]
I don't have a strong opinion about it (for a change!).  I could go either way.

**Comment by DrDaveD** [comment]
This is done
