### ISSUE TITLE
set mountpoint for data partition

### ISSUE THREAD

**Issue by aipolly** [apptainer/sif#194]
sif format cat hold multiple Squashfs,  and the type of partition can be defined by --parttype, is  it possible to define a mount point for non-system partion and auto-mount it  when using apptainer exec/run?

**Comment by DrDaveD** [comment]
No, I don't think that is the case.  It could be put into an environment variable APPTAINER_BIND though, following the syntax shown in the -B option in the [documentation](https://apptainer.org/docs/user/latest/bind_paths_and_mounts.html#sif-image-files).

**Comment by aipolly** [comment]
current iam using commands like 'apptainer exec  --mount type=bind,src=inputs.sif,dst=/data,image-src=/,id=6 inputs.sif' 
with the sif  showing twice looks a little strange， still thanks
