### ISSUE TITLE
Remove unused structs

### ISSUE THREAD

**Issue by sashayakovtseva** [apptainer/sif#57]
Those are not used. We should either leverage them, or remove.

```
// Deffile represents the SIF definition-file data object descriptor.
type Deffile struct {
}

// Labels represents the SIF JSON-labels data object descriptor.
type Labels struct {
}

// Envvar represents the SIF envvar data object descriptor.
type Envvar struct {
}
```

**Comment by ikaneshiro** [comment]
These are unused, but they're technically part of the package API. So this would require a major version bump?

**Comment by sashayakovtseva** [comment]
Hm, let's think about this one.
Those are not used in SIF itself, so nothing would change.

From the end-user perspective this removal can actually affect the API if the structs are used. But those cannot be use b/c they are empty... In other words, to use them in a reasonable way one would need to clone the repo and add some fields.

Technically, changing public API requires new major version, but in this particular case this API part is dead. Thus I am not sure major is needed, IMO patch is enough.

**Comment by ikaneshiro** [comment]
Given the only use for these structs is to serialize data for the `Extra` field of SIF descriptors, and nothing in this tooling is actually using these empty structs, I think it's fine as well. 

These structs only really serve as indicators that the given descriptor type doesn't have data in the `Extra` field.
