### ISSUE TITLE
Use logrus for logging

### ISSUE THREAD

**Issue by sashayakovtseva** [apptainer/sif#64]

**Comment by jscook2345** [comment]
@sashayakovtseva I think we should come up with a list of modules we consider `standard` for our projects. This would be a good start. What do you think @sashayakovtseva ?

**Comment by sashayakovtseva** [comment]
Agree, but then the question is about sylog.
I remember @bauerm97 said sylag was going to be changed as well.

**Comment by tri-adam** [comment]
Given that SIF is used as a library in other components, perhaps it would be nicer to log via an `interface`, and let callers supply their preferred implementation? This, as [Dave Cheney suggests](https://dave.cheney.net/2017/01/23/the-package-level-logger-anti-pattern), avoids coupling the module to any particular logging package. While some may prefer [logrus](https://godoc.org/github.com/sirupsen/logrus), others may prefer something else (Singularity still [implements its own, custom logging package](https://github.com/hpcng/singularity/tree/master/pkg/sylog).)

**Comment by dctrud** [comment]
Agreed... particularly as `scs-library-client` is already using https://github.com/go-log/log as that interface...

https://github.com/sylabs/scs-library-client/blob/404bac8ee4ccc489f6fa3f74bc37b9d3720a1dfb/client/client.go#L15
