### ISSUE TITLE
SPELLING: enviroments -> environments in README.md

### ISSUE THREAD

**Issue by HenrikBengtsson** [apptainer/sif#93]
FYI, the README.md use "enviroments", which should be "enviro[n]ments"

**Comment by PaulCharlton** [comment]
fixed in 3a873bce51f897f5ad9745389aa80b23c16f0df1

**Comment by PaulCharlton** [comment]
@DrDaveD @ikaneshiro @cclerget @kmuriki this was fixed in previous commit ^^^

**Comment by DrDaveD** [comment]
Fixed in #105
